[package]
name = "voxon"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4.0"
winit = "0.30.12"
frametime = { path = "../frametime" }
toml = "1.1.2"
project = { version = "0.1.0", path = "../project" }
webgpu = { version = "0.1.0", path = "../webgpu" }
graphic = { path = "../graphic" }
lina = { path = "../lina" }
format = { version = "0.1.0", path = "../format" }
mesh = { version = "0.1.0", path = "../mesh" }
